Repository 7days-routrip/routrip, pull requests merged in 2024-05, with the labels that each got.

#184 [fix]: 내가 찜한 장소 api 연동 테스트에서 발생한 버그 해결/[refactor]: 지도 컴포넌트, mapStore 코드 개선
  client/src/components/map/ScheduleGoogleMap.tsx
  client/src/components/schedule/AddNewPlace.tsx
  client/src/components/schedule/BookmarkPlace.tsx
  client/src/components/schedule/DaySchedule.tsx
  client/src/components/schedule/PlaceItem.tsx
  client/src/components/schedule/PlaceTabs.tsx
  client/src/components/schedule/SelectPlace.tsx
  client/src/hooks/useBookmarkPlaces.ts
  client/src/hooks/useScheduleDetails.ts
  client/src/models/place.model.ts
  client/src/pages/SchedulePage.tsx
  client/src/stores/mapStore.ts
  client/src/utils/convertDataType.ts
Labels: bug, enhancement, refactor

#186 feat: 장소 상세조회에서 찜하기 여부 조회기능 추가
  server/src/controller/spots.ctl.ts
  server/src/middlewares/authentication.ts
  server/src/routes/spots.routes.ts
  server/src/service/spots.service.ts
  server/src/types/spots.types.ts
Labels: enhancement, feat

#189 fix: 일정 상세보기와 수정페이지에서 헤더에 있는 '내 여행' 클릭하여 일정 등록페이지에 들어온 경우 발생한 버그 해결
  client/src/pages/SchedulePage.tsx
Labels: bug

#194 [refactor]: 일정 페이지 리팩토링/[fix]: 마커 생성하는 함수 버그 해결(createMarkers)
  client/src/apis/place.api.ts
  client/src/components/map/ScheduleGoogleMap.tsx
  client/src/hooks/useScheduleEdit.ts
  client/src/models/place.model.ts
  client/src/pages/SchedulePage.tsx
Labels: bug, refactor

#198 refactor: 라우터 경로 접근 제한 라우터로 코드 개선
  client/src/routes/router.tsx
Labels: enhancement, refactor

#200 bug : profileEdit 프리뷰 수정
  client/src/apis/mypage.api.ts
  client/src/components/common/MypageTabItem.tsx
  client/src/components/common/postCard.tsx
  client/src/pages/ProfileEditPage.tsx
Labels: bug

#212 [feat]: 장소 찜 모달 컴포넌트 구현, 장소 찜 요청 및 삭제 api 구현
  client/src/apis/main.api.ts
  client/src/apis/place.api.ts
  client/src/components/common/LikePlaceCard.tsx
  client/src/components/common/PlaceModal.tsx
  client/src/constants/queryKey.ts
  client/src/hooks/usePlaceDetails.ts
  client/src/styles/theme.ts
Labels: feat, style

#214 Fix/main page
  client/src/apis/main.api.ts
  client/src/components/common/MainPostCard.tsx
  client/src/components/common/PlaceModal.tsx
  client/src/pages/MainPage.tsx
  client/src/styles/customConfirm.css
Labels: bug, style

#216 deploy: 서버측 package.json, tsconfig.json 빌드용 설정 추가
  server/package.json
  server/tsconfig.json
Labels: deploy

#217 fix: 일정 등록,수정, 장소 검색 버그 수정
  server/src/service/journeys.service.ts
  server/src/service/spots.service.ts
Labels: bug

#218 [refactor]: 지도 중심점 초기화 되지 않는 문제 해결/[style]: 일정 등록 버튼 위치 수정
  client/src/components/schedule/PlaceTabs.tsx
  client/src/components/schedule/SearchBox.tsx
  client/src/hooks/useScheduleEdit.ts
  client/src/pages/ScheduleEditPage.tsx
  client/src/pages/SchedulePage.tsx
Labels: refactor, style

#221 refactor: 작업한 API 메시지 상수로 변경
  server/src/constants/message.ts
  server/src/controller/comments.ctl.ts
  server/src/controller/users.ctl.ts
  server/src/service/comments.service.ts
  server/src/service/users.service.ts
Labels: refactor

#226 [refactor]: 마이페이지에서 사용되는 장소 찜 모달 컴포넌트에 전달되는 `onClosed` 함수 수정
  client/src/apis/https.ts
  client/src/apis/schedule.api.ts
  client/src/components/common/LikePlaceCard.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/Mypage.tsx
Labels: enhancement, refactor

#227 [refactor]: 버그 수정 및 기능 리팩토링, css 수정
  client/src/components/common/CategoryCard.tsx
  client/src/components/common/MainPostCard.tsx
  client/src/components/common/PlaceModal.tsx
  client/src/components/common/ProfileCard.tsx
  client/src/components/common/postCard.tsx
  client/src/pages/Mypage.tsx
  client/src/pages/PostDetailPage.tsx
  client/src/pages/PostPage.tsx
  server/src/controller/posts.ctl.ts
  server/src/controller/users.ctl.ts
  server/src/models/places.model.ts
  server/src/models/posts.model.ts
  server/src/service/comments.service.ts
  server/src/service/likes.service.ts
  server/src/service/posts.service.ts
  server/src/service/spots.service.ts
  server/src/types/posts.types.ts
Labels: bug, feat, refactor

#228 [refactor]: post 모델 오타 수정
  client/src/models/post.model.ts
Labels: refactor

#233 fix: 코멘트 카드 수정
  client/src/components/common/Comment.tsx
Labels: feat

#237 [style]: 글쓰기 버튼과 top버튼 스타일 수정
  client/src/components/common/WriteTopBtn.tsx
Labels: style

#238 deploy: github-action으로 CI-CD 배포 자동화 구축
  .github/workflows/aws-be.yml
  .github/workflows/aws-fe.yml
  .gitignore
  client/Dockerfile
  client/vite.config.ts
  server/Dockerfile
  server/src/settings.ts
Labels: deploy

#240 fix: 프론트 빌드 문제 해결
  client/tsconfig.json
Labels: bug

#242 fix: client port 수정
  .github/workflows/aws-fe.yml
  client/Dockerfile
Labels: bug

#243 fix: client 도커파일 수정
  client/Dockerfile
Labels: bug

#245 fix : postComment 수정
  client/src/components/common/MainPostCard.tsx
  client/src/components/common/PostComment.tsx
  client/src/icons/icons.ts
  client/src/pages/PostDetailPage.tsx
Labels: refactor, style

#246 deploy: client ssl 적용
  .github/workflows/aws-fe.yml
  client/.gitignore
  client/Dockerfile
Labels: deploy

#261 bug 사용자 정보 페이지 수정
  client/src/components/common/postCard.tsx
  client/src/hooks/useAuth.ts
  client/src/pages/ProfileEditPage.tsx
  client/src/pages/ProfileResetPassword.tsx
  client/src/pages/ResetPassword.tsx
Labels: bug, style

#263 [refactor]: 로그인하지 않은 사용자가 로그인이 필요한 페이지 경로에 접근 시 커스텀 alert창이 보이게 수정
  client/src/routes/router.tsx
Labels: enhancement, refactor

#267 [feat]: 메인페이지 루트립의 추천루트 api 구현
  client/src/apis/main.api.ts
  client/src/components/common/GuidePostCard.tsx
  client/src/hooks/useMain.ts
  client/src/pages/MainPage.tsx
Labels: feat

#271 [fix]: 루트립의 추천루트 쿼리키 수정
  client/src/constants/queryKey.ts
  client/src/hooks/useMain.ts
Labels: bug

#278 fix: 일정이 포스팅에 첨부되어있을 경우 수정이 되지 않는 버그 수정
  server/src/service/journeys.service.ts
Labels: bug

#284 [fix]: 일정 상세보기 페이지에서 일정 삭제 성공 시 마이페이지 일정 모음 페이지로 이동하는 경로 수정
  client/src/hooks/useScheduleDelete.ts
  client/src/pages/PostDetailPage.tsx
Labels: bug

#287 fix: github action 실행 설정 변경
  .github/workflows/aws-be.yml
  .github/workflows/aws-fe.yml
Labels: bug, deploy
